routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// -------Master-----
use App\Http\Controllers\Admin\StandardMasterController;
use App\Http\Controllers\Admin\CastMasterController;
use App\Http\Controllers\Admin\DistanceMasterController;
use App\Http\Controllers\Admin\DocumentsMasterController;
use App\Http\Controllers\Admin\ReligionMasterController;
use App\Http\Controllers\Admin\TermsConditionController;
use App\Http\Controllers\Admin\SeatMasterController;
use App\Http\Controllers\Admin\NotificationMasterController;

use App\Http\Controllers\Master\SchoolController;
use App\Http\Controllers\Master\FinancialYearController;

// -----Admin-------
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminRegisterController;
use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\AdminApplicationController;
// ------User-------
use App\Http\Controllers\User\LoginController;
use App\Http\Controllers\User\RegisterController;
use App\Http\Controllers\User\ApplicationController;

// use App\Http\Controllers\HomeController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// -----User-----
 Route::get('login', [LoginController::class, 'login']);
Route::get('/', [LoginController::class, 'landingpage']);
Route::post('dologin', [LoginController::class, 'dologin']);
Route::get('register', [RegisterController::class, 'create']);
Route::post('register', [RegisterController::class, 'store']);
// ----end-----
Route::group(['middleware' => ['baseuser']], function () {

Route::get('admin/index', [AdminController::class, 'index']);
Route::get('logout', [AdminController::class, 'logout']);
Route::get('admin/pdf', [AdminController::class, 'pdf']);
//-----User Panel------
Route::resource('student_application', ApplicationController::class);
Route::get('school_list', [ApplicationController::class, 'schoolList']);
Route::get('termsandconditions/{id}', [ApplicationController::class, 'termsAndCondition']);
Route::post('/get-cast', [ApplicationController::class, 'get_cast']);

Route::get('create/{id}', [ApplicationController::class, 'create']);


    //-------Admin Panel------
    Route::resource('/admin_register', AdminRegisterController::class);
    Route::resource('/application_list', AdminApplicationController::class);
    //------Master-------
    Route::resource('/standard_master', StandardMasterController::class);
    Route::resource('/cast_master', CastMasterController::class);
    Route::resource('/religion_master', ReligionMasterController::class);
    Route::resource('/distance_master', DistanceMasterController::class);
    Route::resource('/documents_master', DocumentsMasterController::class);
    Route::resource('/school', SchoolController::class);
    Route::resource('/financial_year', FinancialYearController::class);
    Route::resource('/terms_condition', TermsConditionController::class);
    Route::resource('/seat_master', SeatMasterController::class);
    Route::resource('/notification_master', NotificationMasterController::class);
    //----end----
    Route::get('/generate_pdf/{id}', [AdminApplicationController::class, 'generate_pdf'])->name('generate_pdf');

    Route::get('/view_generate_pdf/{id}', [AdminApplicationController::class, 'view_generate_pdf'])->name('view_generate_pdf');

    // application list pending/approve/reject
    Route::get('/status_application_list/{status}', [AdminApplicationController::class, 'applicationStatusList'])->name('applicationStatusList');
    Route::get('/view_application/{id}', [AdminApplicationController::class, 'viewapplicationStatusList'])->name('viewapplicationStatusList');
    Route::get('/approve_application/{id}', [AdminApplicationController::class, 'ApproveApplication'])->name('ApproveApplication');
    Route::post('/reject_applicationbyclerk/{id}', [AdminApplicationController::class, 'rejectApplicationbyclerk'])->name('rejectApplicationbyclerk');
    Route::get('/app_pool_list', [AdminApplicationController::class, 'AppPullList'])->name('AppPullList');
    Route::get('/application_report', [AdminApplicationController::class, 'applicationReportlist'])->name('applicationReportlist');
    Route::get('/reservation_report', [AdminApplicationController::class, 'reservationReport'])->name('reservationReport');
    Route::get('/pool_process', [AdminApplicationController::class, 'poolProcess'])->name('poolProcess');
    Route::get('/random_selection', [AdminApplicationController::class, 'randomselection'])->name('randomselection');

    Route::get('/view_documents/{id}', [AdminApplicationController::class, 'view_documents'])->name('view_documents');
});

resources/views/Admin/religion/create.blade.php
@extends('layouts.master')

@section('content')

	<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
			<div class="container-fluid">
				<div class="row">

				</div>
				<div class="col-xl-12">
					<div class="card">
						<div class="card-header">
							<h5 class="mb-0">Add Religion </h5>
						</div>

						<div class="card-body">
                            <form method="post" action="{{ url('/religion_master') }}" class="new-added-form needs-validation" enctype="multipart/form-data">
                                @csrf

							<div class="row">
								<div class="col-xl-8 col-sm-6">
									<div class="mb-3">
									  <label for="exampleFormControlInput9" class="form-label text-primary">Religion Name <span class="required">*</span></label>
									  <input type="text" class="form-control"  name="religion_name" id="religion_name" placeholder="Enter Religion " required>
									</div>

								</div>

							</div>
							<div class="float-end">
								<button class="btn btn-outline-primary me-3">Cancle</button>
								<button class="btn btn-primary" type="submit">Save</button>
							</div>
                        </form>
						</div>

					</div>
				</div>
			</div>
		</div>
        <script>
            (function () {
              'use strict'

              // Fetch all the forms we want to apply custom Bootstrap validation styles to
              var forms = document.querySelectorAll('.needs-validation')

              // Loop over them and prevent submission
              Array.prototype.slice.call(forms)
                .forEach(function (form) {
                  form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                      event.preventDefault()
                      event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                  }, false)
                })
            })()
        </script>
        <!--**********************************
            Content body end
        ***********************************-->

@endsection

resources/views/Admin/religion/edit.blade.php
@extends('layouts.master')

@section('content')

	<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
			<div class="container-fluid">
				<div class="row">

				</div>
				<div class="col-xl-12">
					<div class="card">
						<div class="card-header">
							<h5 class="mb-0">Edit Religion </h5>
						</div>

						<div class="card-body">
                            <form method="post" action="{{ route('religion_master.update', $data->id) }}" class="new-added-form" enctype="multipart/form-data">
                                @csrf
                            @if (!empty($data->id) || 1 == 1)
                                <input type="hidden" name="_method" value="PATCH">
                            @endif

                            <input type="hidden" id="id" name="id" value="{{ $data['id'] or '' }}">
							<div class="row">
								<div class="col-xl-6 col-sm-6">
									<div class="mb-3">
									  <label for="exampleFormControlInput9" class="form-label text-primary">Religion Name <span class="required">*</span></label>
									  <input type="text" class="form-control" value="{{ $data->religion_name }}" name="religion_name" id="religion_name" placeholder="Enter religion_name">
									</div>

								</div>

							</div>
							<div class="float-end">
								<button class="btn btn-outline-primary me-3">Cancle</button>
								<button class="btn btn-primary" type="submit">Save</button>
							</div>
                        </form>
						</div>

					</div>
				</div>
			</div>
		</div>

        <!--**********************************
            Content body end
        ***********************************-->

@endsection

resources/views/Admin/religion/grid.blade.php
@extends('layouts.master')

 @section('content')

 <div class="content-body">
            <!-- row -->
			<div class="container-fluid">
				<!-- Row -->
				<div class="row">

                <!-- Column starts -->

                <!-- Column ends -->
                <!-- Column starts -->
                <div class="col-xl-12">
                    <div class="card" id="accordion-three">
                        <div class="card-header flex-wrap d-flex justify-content-between px-3">
                            <div>
                            <h4 class="card-title">Religion List</h4>

                            </div>
                            <ul class="nav nav-tabs dzm-tabs" id="myTab-2" role="tablist">
                                <li class="nav-item" role="presentation">
                                <!-- Button trigger modal -->
                               <a href="{{ route('religion_master.create') }}"><button type="button" class="btn btn-primary" >
                                 + Add Religion
                                </button></a>
                                </li>

                                </ul>
                                </div>

                                <!-- /tab-content -->
                                <div class="tab-content" id="myTabContent-2">
                                <div class="tab-pane fade show active" id="withoutSpace" role="tabpanel" aria-labelledby="home-tab-2">
                                <div class="card-body p-0">
                                <div class="table-responsive">
                                <table id="example3" class="display table" style="min-width: 845px">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Religion Name</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($religion as $key => $value)
                                    <tr>
                                        <td><b>{{ $key+1 }}</b></td>
                                        <td><b>{{ $value->religion_name }}</b></td>

                                        <td>
                                            <div class="d-flex">
                                                <a href="{{ route('religion_master.edit', $value->id) }}" class="btn btn-primary shadow btn-xs sharp me-1"><i class="fas fa-pencil-alt"></i></a>
                                                <form action="{{ route('religion_master.destroy', $value->id) }}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <input name="_method" type="hidden" value="DELETE">
                                                  <button class="btn btn-danger shadow btn-xs sharp" onclick="return confirm('Are you sure to delete?')"><i class="fa fa-trash"></i>
                                                  </button>
                                               </form>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach


                                </tbody>
                            </table>
                            </div>
                                    </div>
                                </div>

                                </div>
                            </div>
                            <!-- /tab-content -->

                    </div>
                </div>



        </div>
    </div>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script type="text/javascript">
    function confirmation() {
        var result = confirm("Are you sure to delete?");
        if (result) {
            // Delete logic goes here
        }
    }
</script>

@endsection